on:
  push:
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          for x in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          do 
          echo $x
          done