name: automatic tester

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: git fetch
      run: | 
        git fetch
    - name: Clear Cache
      run: |
        git clean -ffdx
        rm -rf ${{ runner.workspace }}/path/to/cache
    - name: Debugging Output
      run: |
        git log --oneline
        git show-ref
    - name: Checkout Specific Commit
      run: |
        git checkout ${{ github.event.before }}
    - name: existance check 
      run: |
        git cat-file -t ${{ github.event.before }}
    - name: existance check2
      run: |
        git cat-file -t ${{ github.event.after }}
    - name: test diff
      run: | 
        git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
    - name: Test with pytest
      run: |
        unique_list=()
        git fetch
        for x in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
        do
          pos=$(echo "$x" | grep -b -o "tests/" | cut -d: -f1)
          if [ -n  "$pos" ]; then
            testpath="${x:0:$pos+6}"
            if [[ ! " ${unique_list[@]} " =~ " $testpath " ]]; then
              unique_list+=("$testpath")
            fi
          fi
        done

        for unique_item in "${unique_list[@]}"; do
          pytest $unique_item
        done