name: automatic tester

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
      with:
        # checkout full tree
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openapi-spec-validator
    - name: Test with pytest
      run: |
        unique_list=()
        git fetch
        for x in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
        do
          pos=$(echo "$x" | grep -b -o ".yml" | cut -d: -f1)
          if [ -n  "$pos" ]; then
            testpath="${x:0:$pos+6}"
            if [[ ! " ${unique_list[@]} " =~ " $testpath " ]]; then
              unique_list+=("$testpath")
            fi
          fi
        done

        for unique_item in "${unique_list[@]}"; do
          openapi-spec-validator $unique_item
        done